Feature/#1 init typescript settings
rete-academy/dashboard pull request #6
Opened 2020-11-13 03:15 UTC by techntv

- Init project with NextJS and Typescript.
- Setting Enlint for Typescript.
- Add pages, components, utils folder.
- Modify gitignore file.

2020-11-13 07:12 UTC, sangdth requested changes
Mọi thứ trông có vẻ ok, chỉ thay một xíu là được.

2020-11-13 07:12 UTC, sangdth commented on tsconfig.json
> +        "~/*": ["./*"]
Nên dùng `@` thay cho `~` vì trong hầu hết unix based machines, `~` tượng trưng cho `home` folder.

Trong typescript thực ra ký tự nào cũng không quan trọng, nó cứ map ra thôi, nhưng trong lúc code, nếu người mới vào, họ đọc thấy ví dụ `import sthing from '~/somewhere` họ sẽ tưởng là import trực tiếp từ local home folder.

2020-11-13 07:12 UTC, duy211099 reviewed
👍

2020-11-16 01:28 UTC, techntv commented
Em mới update code, anh Sang merger giúp em nhé

2020-11-16 09:31 UTC, merged

2020-11-16 09:32 UTC, sangdth commented
🎉